version: 2.1

commands:

  cancel-if-redundant-workflow:
    steps:
        - run: 
            name: Cancel if workflow has run already for this commit
            background: true
            command: |
                bash cancel-workflow.sh
                
  cancel-if-new-commit:
    steps:
      - run:
          name: Check for newer workflow...
          background: true
          command: |
             while true; do
                LATEST_COMMIT=$(git ls-remote $CIRCLE_REPOSITORY_URL | grep $CIRCLE_BRANCH | cut -f 1)
                if [ "$LATEST_COMMIT" != "$CIRCLE_SHA1" ]; then
                    echo "more recent commit to branch, exiting..."
                    curl -X POST "https://circleci.com/api/v2/workflow/$CIRCLE_WORKFLOW_ID/cancel?circle-token=$CIRCLE_TOKEN"
                fi
             done


jobs:
  test-redundant-cancellation:
      docker:
        - image: cimg/base:stable
      resource_class: small
      steps:
        - checkout
        - cancel-if-new-commit
        - cancel-if-redundant-workflow
        - run: sleep 300

workflows:
  main:
    jobs:
      - test-redundant-cancellation
