version: 2.1

commands:

  cancel-if-redundant-workflow:
    steps:
        - run: 
            name: Cancel if workflow has run already for this commit
            background: true
            command: |
                bash cancel-workflow.sh

jobs:
  test-redundant-cancellation:
      docker:
        - image: cimg/base:stable
      resource_class: small
      steps:
        - checkout
        - cancel-if-redundant-workflow
        - run: sleep 300

workflows:
  main:
    jobs:
      - test-redundant-cancellation
