version: 2.1
jobs:
  test-job:
      docker:
        - image: cimg/base:stable
      steps:
        - checkout
        - run: 
            name: Cancel if workflow has run already for this commit
            command: |
                echo "hello"
                #bash cancel-workflow.sh
workflows:
  main:
    jobs:
      - test-job
